#!/bin/bash

DRIVER_OPTS="-d virtualbox"
SLEEP=1
NETS="overlay_services"
NETP="overlay_production"
NUM=2 #Number of Hosts and Nodes
[ -z "$WORKING_DIR" ] && WORKING_DIR=$(pwd)
[ -z "$DNSMASQ_DIR" ] && DNSMASQ_DIR="$WORKING_DIR/../docker-dnsmasq"

pwd
echo "====> Call Server Script"
cd "$WORKING_DIR"
/script/setup
pwd

echo "====> Call Server Script"
cd "$WORKING_DIR"
/script/server

eval $(docker-machine env Host0)
for (( i = 0; i < $NUM; i++ )); do
	echo "********* Pinging from Node0 to Node$i"
	docker exec "Node0" ping -c 2 "Node$i"
done